version: "3.8"

services:
  mongo:
    image: mongo:5.0
    container_name: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: studentmanagement
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
    container_name: backend
    restart: unless-stopped
    environment:
      - MONGODB_URI=mongodb://mongo:27017/studentmanagement
      - PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    restart: unless-stopped

volumes:
  mongo-data:
